# =============================
# Server
# =============================
server:
  port: 8080

# =============================
# Spring Boot Main Config
# =============================
spring:
  application:
    name: myfin-app

  # ================
  # Datasource / DB
  # ================
  datasource:
    url: jdbc:postgresql://localhost:5432/myfin_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  # ================
  # Flyway
  # ================
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true # DEV - change false on PROD

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect:
          default_param_cast: true
    show-sql: false

  jackson:
    serialization:
      write-dates-as-timestamps: false # use ISO format

# ================
# Logging
# ================
logging:
  level:
    root: INFO
    com.tafh.myfin_app: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

# ================
# Properties
# ================
security:
  cookie:
    secure: false # change to true if production
jwt:
  secret: "SUPER_SECRET_KEY_MIN_32_CHARACTERS_LONG"
  issuer: "ecommerce-api"
  expiration: 3600000 # 3600000 1 hour
  refresh-expiration: 2592000000 # 30 hari
